name: Common SDK publish from master or support branch

on:
  pull_request:
    types: [closed]
    branches:
      - 'master'

jobs:
  publish-MindboxCommon:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}
      - name: Update bundler
        run: gem install bundler
      - name: Install bundler dependencies
        run: bundle install
      - name: Deploy to Cocoapods MindboxLogger
        run: |
#          pod lib lint MindboxCommon.podspec --allow-warnings
#          pod trunk push MindboxCommon.podspec --allow-warnings --verbose
          echo '✅ 💚 Mock published MindboxCommon'
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
          
