name: Common SDK publish from master or support branch

on:
  pull_request:
    types: [closed]
    branches:
      - 'master'

jobs:
  publish-MindboxCommon:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.ref_name }}

      - name: Install required gems
        run: |
          gem install cocoapods xcodeproj
          pod --version

      - name: Deploy to Cocoapods MindboxLogger
        run: |
          echo '🔥 ✅ TEST '
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TOKEN }}
